### PR TITLE
Cheats

### PR DESCRIPTION
**Pull request by SuuperW**
Implement request #178, along with a couple other cheat list related features.

I'm not sure if all the commits here are correct. Once my previous PR is merged I will fix this PR if necessary.

### CODE REVIEW

**Comment by SuuperW** [comment]
The AppVeyor build failed, but the code builds just fine on my machine (Win10, VS2017).
The error is "cheatSystem.cpp(82): error C2039: '_Make_iterator_offset': is not a member of 'std::vector<CHEATS_LIST,std::allocator<_Ty>>'".
I do not see why it can't find the _Make_iterator_offset method. Does anyone else know?

**Comment by zeromus** [comment]
your move() implementation is really weird. Find a more normal way of doing it. That's some kind of internal implementation detail you've used on the STL type.

Also, I know it's annoying, but when you've got multiple PR in flight like this, you should probably base the branch on origin/master, rather than suuperw/master, so the changes can be considered in isolation rather than along with all your other edits to master. I'm not asking you to change it though. However, something small like this could get hung up waiting for the bigger PR to get done

**Comment by SuuperW** [comment]
I've updated the move method, and the automatic build is successful now.

**Comment by SuuperW** [comment]
I've fixed the PR.

**Comment by JTR425** [comment]
sorry if it was extremely obvious but how do i move cheats?

**Comment by zeromus** [comment]
drag them, or edit the .dct file

**Comment by JTR425** [comment]
do i have to hold down say shift or something when dragging? also how do i edit the dct file. sorry if these are bad questions i only just downloaded desmume and have no experience in this

**Comment by JTR425** [comment]
sorry to be a bother i figured it out thanks for the help anyways

**Pull request merged**
