### PR TITLE
Refactor+Bugfixes

### PR DESCRIPTION
**Pull request by SuuperW**
Sorry for the merging mess. I don't understand how to do this stuff with Git, and don't know why it can't marge automatically. I merged TASVideos master branch into mine. If there's something I should do differently with Git, let me know.

For info on what's changed, see the commits.

### CODE REVIEW

**Comment by retr0s4ge** [comment]
I had a similar sitiuation a while ago. I resolved it before creating a pull request, but the steps to fix this will be the same.

Take a local backup of all your work then do the following:

git checkout master

git remote add upstream https://github.com/TASVideos/desmume.git
git fetch upstream
git rebase −p upstream/master

the rebase operation will stop at every conflicting commit and prompt to open code editor to resolve the conflict

after resolving each conflict, continue with

git rebase --continue

(this will need to be repeated for every conflict)

now your local branch will be up to date, and all the new commits will appear as outgoing.

force push to your fork with

git push origin master -f 

your pull request should be fixed after that.

Note that I was working on master branch, If you are working on a different branch replace "master" with your branch name except when referencing upstream/master.

**Comment by zeromus** [comment]
yes, rebase is usually better than merge. i never merge, personally, during my main development. but rebasing is 100000000000000000 more steps

**Comment by SuuperW** [comment]
@zeromus I do not know how to reset my branch to yours.

@retr0s4ge The first commit it wanted me to do after resolving conflicts was a merge commit. Was this expected?

**Comment by zeromus** [comment]
for me, it would be:
backup everything, and then:
tortoise git > browse references > refs > remotes > origin > suuper refactor [rightclick] show log > rightclick latest commit > reset master to this
then, analyze it.
then, if it's good, force-push it to your repo

**Comment by retr0s4ge** [comment]
@SuuperW I see you re-based and resolved all the conflicts, so you are almost done!
Now to remove the merge commit `165d3a3` and select the correct parent for `f2283f9` do the following:

`git checkout refactor`
`git branch refactorBackup`
`git reset --hard 6fa6467c`
`git cherry-pick f2283f91 -m 2`
`git cherry-pick 48b40e5 9c8fd32 eb35e89 69a6a99 572673e 3b061bb 045b406 457627c db17103 7d43e97`
`git push origin refactor -f`

The local branch refactorBackup will contain all the commits in their current state (as a backup).

**Comment by SuuperW** [comment]
When I did "git cherry-pick f2283f91 -m 2", I got this error:
"fatal: bad revision 'f2283f91'"

I don't know if this is related, but when I did "git checkout refactor", main.cpp got very messed up. It had some parts being correct with recent commits from myself and from others, some parts being outdated versions of code, and some git metadata stuff. I reverted changes since the last commit before continuing.

**Comment by retr0s4ge** [comment]
The checkout probably failed as you have uncommitted changes on master branch. You can force the checkout by adding -f but you will lose any uncommitted changes on master branch.

I successfully did the following on my PC:

**1-** Create a new directory called SuuperW
`mkdir SuuperW`

**2-** Switch to the new directory
`cd SuuperW`

**3-** Clone your desmume fork
`git clone https://github.com/SuuperW/desmume.git`

**4-** Switch to the desmume directory
`cd desmume`

**5-** Force checkout the refactor branch
`git checkout refactor -f`

**6-** Create a new branch "refactorBackup"
`git branch refactorBackup`

**7-** Reset to the last upstream commit tree
`git reset --hard 6fa6467c`

**8-** Cherry pick the relevant commits
`git cherry-pick f2283f91 -m 2`

**9-** then
`git cherry-pick 48b40e5 9c8fd32 eb35e89 69a6a99 572673e 3b061bb 045b406 457627c db17103 7d43e97`

As I don't have write access to your repository, I pushed the refactor branch to mine by changing the push URL before pushing. **(Do NOT do this)**
`git remote set-url --push origin https://github.com/retr0s4ge/desmume.git`

**10-** Force push to your refactor branch
`git push origin refactor -f`

The result is the same code modifications you have in this PR but with only 11 commits and a clean git history.
Check the result here: 
https://github.com/retr0s4ge/desmume/commits/refactor
And here is how pull request commits will look like:
https://github.com/TASVideos/desmume/compare/master...retr0s4ge:refactor

Note: The "SuuperW authored and retr0s4ge committed" message will not be present in your case.

**Comment by zeromus** [comment]
if it's done right, then result is probably the same friggin thing i already did, check the result here
https://github.com/TASVideos/desmume/tree/suuper-refactor

all i did is PROPERLY merge master onto his last useful commit. when main.cpp conflicted, i simply pasted over the main.cpp from his bad history, which I assume he resolved fine (the only problem was the history).

**Comment by retr0s4ge** [comment]
@zeromus Sorry, I should have been more clear.

Other than getting the PR merge issue fixed, I was trying to help remove the merge commits (and some trailing old commits) from appearing in desmume's git history if this PR is merged.

The only way I know of is to cherry pick the useful commits, so I suggested he re-base to fix the code confilcts, then hard reset to upstream and cherry pick the useful commits to have a clean git history.

Whether he re-based on master or hard reset to a separate branch to fix the code conflicts; I think he will then need to hard reset to master anyway then cherry-pick the useful commits to have a clean git history.

**Comment by SuuperW** [comment]
@retr0s4ge Looks like I got it to work now. The order of commits in my local repository somehow didn't match the origin, so I did a pull. After that, your steps worked just fine.

@zeromus As I mentioned in my edit above, the code in my original PR (and thus your suuper-refactor branch) was incorrect. Since I'm pretty certain that the one incorrect piece of code I happened to notice was not a conflict I manually resolved but something Git did automatically during the merge, I have no way to know what else might be wrong. Thus I think that retr0s4ge's method of fixing things is preferable. I do appreciate your help, though.

**Comment by SuuperW** [comment]
@zeromus @rogerman Would one of you please review/merge this PR? I'm not aware of any significant problems with the new code or of any regressions.

**Comment by rogerman** [comment]
Just tested the all changes. Everything seems to work as it should. I can also confirm that LUA script drawing works fine.

**Comment by zeromus** [comment]
so lets get this over with

**Comment by zeromus** [comment]
so let's get this over with

**Pull request merged**
