### PR TITLE
(Windows Frontend) Add an option to display menu in fullscreen mode.

### PR DESCRIPTION
**Pull request by retr0s4ge**
This should eliminate the need to keep toggling fullscreen mode on/off to change settings.

### CODE REVIEW

**Comment by retr0s4ge** [comment]
As a useful side effect while this setting is enabled, WDWM's triple buffering and vsync will be applied in fullscreen mode on windows 8 and 10 (And supposedly, windows 7 if Aero theme is enabled).
So, this can also be used as a workaround for #164

**Comment by zeromus** [comment]
solve it always by making the pseudo-fullscreen window 1 pixel smaller, or something like that. see "enable windows fullscreen hacks" in bizhawk, although we're far from cutting edge in bizhawk OR desmume. in both cases we have mountains of legacy cruft to deal with so we can't really incorporate modern best practices.......whatever those are.........

**Comment by retr0s4ge** [comment]
Thanks for the pointers, I will check that as a primary solution for #164 

If we disregard the side effect, what's your opinion on having the option to display the menu in fullscreen mode ?

I think the menu has a fairly low profile, and can be convenient in case the user wants to change a setting without leaving fullscreen.

**Comment by zeromus** [comment]
windows has no such feature. you have to code it yourself.

I don't care if there's a menu in fullscreen mode. Some people might. Dont do this just as a lark, or as a workaround when there's the other workaround I mentioned. If someone wants this, then it's worth doing. That is, if working on the desmume frontend at all rather than rewriting it is worth doing in the first place. I don't think so, but do what you want with your time. Just beware the first time someone actually rolls up their sleeves and rebuilds the windows frontend, all your code will probably be deleted.

One thing bizhawk is kind of cutting edge in (or at least comfortably near the front of the pack) is in options for getting work done in windows, which includes this. Consequently, these are all options people have wanted:

image

**Pull request closed without merging**
