### PR TITLE
Add WiFi fix from desmume-reloaded, tweak the wait for display thread added in commit ee8fdeb

### PR DESCRIPTION
**Pull request by retr0s4ge**
Changes:
1- Rebased on TASVideos/desmume  (bd63ff1 tree)
2- Merge WiFi fix for desmume 0.9.12 from desmume-reloaded (commit 7548294)
3-  Forcibly wait for the display thread to draw each frame only if the user set frame skip to 0 (commit 411bcaa)

### CODE REVIEW

**Comment by w4st3d** [comment]
mudlordwhy.jpg

Seriously, why WinPCAP? I must be missing something if it must use that dependancy for sockets in particular.

**Comment by zeromus** [comment]
You're missing that low level networking interfaces are required for this purpose

**Comment by w4st3d** [comment]
Ah, then now it all makes sense.

**Comment by mrwalters1988** [comment]
Since WinPCap is no longer being developed, can we switch the requirementes over to utilize NPCap?

**Comment by zeromus** [comment]
what does whether winpcap is developed have to do with whether we use winpcap

**Comment by MojoJojoDojo** [comment]
it still works with Npcap if you use winpcap API compatibility mode when you install it.

**Pull request merged**
